# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb08cbd7ad2f366025079f605e8c4408f36f8498557b88a05d8d1ce1723b16d504282a307786ee3bdf2d365a363909be94f0600671b7b7750bc99b5301bd282b

test:
  secret_key_base: e486adce7513c25b4e3371a266ab229856d90a63a5c8d21327f3b2bf38d0736babbf20bf52450fca78b818c2e007853b0c3e2acc4efb64433d9582ab23a17ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
